### ISSUE TITLE
Auto-install .rpm version via terminal?

### ISSUE THREAD

**Issue by yioannides** [dropbox/nautilus-dropbox#137]
Hi everyone, I am building a Fedora post-install script and I was wondering if there's a way to automatically download the latest 64-bit .rpm for nautilus-dropbox and install it without physically interacting with the "Install Nautilus extension" dialog box, all via terminal.

I tried extracting the latest 64-bit .rpm link from the [Dropbox Linux install page](https://www.dropbox.com/install-linux) via wget and curl, but since the link name is dynamic based on release date, it always updates, so I was wondering if there's a static way of retrieving the latest version, like the tarball version.

**Comment by jewelpit** [comment]
We don't currently expose a way to always grab the latest, but installing the RPM adds our third-party repo, so installing a specific version then running `dnf upgrade dropbox` (I thiiink DNF lets you upgrade a single package at a time?) will get you on the latest.

As for the dialog box, running `DISPLAY= dropbox start -i` will launch Dropbox in headless mode, so it'll output the dialog box contents to stdout instead of trying to make a dialog box.

**Comment by yioannides** [comment]
Thank you for the response. What I'd like to achieve is automatically installing nautilus-dropbox on the very first reboot after a fresh Linux install via shell, but that would require either retrieving the latest .rpm from a website or adding a third-party repository and downloading nautilus-dropbox from there. Is there at least a way to enable the Dropbox repo via command line?

As for the dialog box, I meant the dialog box that appears during installation that asks the user to enable the Nautilus extension. Since I want to automate the process mentioned above, is there a way to install everything without any further interaction via Terminal? (something like `sudo dnf install -y nautilus-dropbox`)

Otherwise, if I was to use the headless version: 1. would I be able to update it via terminal just like any other application? 2. could I have access to the Dropbox menu like I do via the .rpm version and the AppIndicator extension?

Sorry for the many questions and thank you for your time!
