### ISSUE TITLE
Dropbox tray icon not working in XFCE & LXDE

### ISSUE THREAD

**Issue by acsipak** [dropbox/nautilus-dropbox#15]
[See downstream bug on Launchpad for details.](https://bugs.launchpad.net/ubuntu/+source/nautilus-dropbox/+bug/1546176)

**Comment by J-Moravec** [comment]
Similar problem is with Metacity from Gnome Flashback. However, these fixes do not work. What however works is either runnig dropbox as sudo, but that is less than helpful as Dropbox will set rights to newly modified files in Dropbox to root. The other thing that helps is tricking Dropbox that it is running on Unity (I can't google the solution right now, but I have applied it on one computer at work).

I tried to report it through Dropbox ticket system, but the support was utterly incapable understanding even simple statements (like "No, I don't have unsupported system, I have Ubuntu with Gnome Classic")

**Comment by samertm** [comment]
Hey, sorry for the long delay in fixing this bug. This issue should be fixed in the latest beta build, v64, without the dbus-launch hack (tested on Kubuntu 18.04 and 14.04).

You can download it from this page: https://www.dropboxforum.com/t5/Desktop-client-builds/Beta-Build-64-3-120/m-p/317429

Untar it into your home directory to install it (it will extract everything into .dropbox-dist).

Please re-open if that doesn't fix your issue.
