### ISSUE TITLE
AppIndicator Menu broken in gnome-flashback

### ISSUE THREAD

**Issue by valdr** [dropbox/nautilus-dropbox#35]
In both Metacity and Compiz (Ubuntu 16.04), the appindicator does not show the menu.
Running either **dbus-launch dropbox start** or **DBUS_SESSION_BUS_ADDRESS= dropbox start** will solve the issue, apparently (not tested by me).
Can this not be tested/handled in the py script?

I cannot add the screengrab, but the issue is mentioned **[here](https://askubuntu.com/questions/821061/dropbox-appindicator-menu-broken-in-gnome-flashback#821264)**.

**Comment by samertm** [comment]
Hey, sorry for the long delay in fixing this bug. This issue should be fixed in the latest beta build, v64, without the dbus-launch hack (tested on Ubuntu 18.04 with Gnome Flashback).

You can download it from this page: https://www.dropboxforum.com/t5/Desktop-client-builds/Beta-Build-64-3-120/m-p/317429

Untar it into your home directory to install it (it will extract everything into `.dropbox-dist`).

Please re-open if that doesn't fix your issue.
