### ISSUE TITLE
How to switch between linked dropbox/dropbox-business accounts?

### ISSUE THREAD

**Issue by SebStaeubert** [dropbox/nautilus-dropbox#44]
Hi,

this feature is missing in the recent linux version of the dropbox client, right? Howto switch between 2 accounts in linux like in the windows client?

THX

**Comment by nipunn1313** [comment]
Unfortunately, logging into multiple accounts is not a feature supported on linux. You'll have to pick one or the other to log into.

Some people on the internets appear to have found workarounds, but I can't make any promises about them, since it's not a supported configuration
https://askubuntu.com/questions/475419/how-to-link-and-use-two-or-more-dropbox-accounts-simultaneously

**Comment by SebStaeubert** [comment]
Ok, thank you!
