### ISSUE TITLE
Please switch to GIR bindings

### ISSUE THREAD

**Issue by bigon** [dropbox/nautilus-dropbox#56]
Hi,

pygtk binding is dead, nautilus-dropbox should be switched to GIR bindings and GTK+ 3

The use of old pygtk binding is actually a blocker for #55

Edit: Already using GTK3 actually

**Comment by nipunn1313** [comment]
Thanks for the report. This makes sense to do as part of #55 

It looks like there are some docs here
https://python-gtk-3-tutorial.readthedocs.io/en/latest/

**Comment by bigon** [comment]
The last version of my patch is the good one

Quickly testing here it works

**Comment by rsvp** [comment]
Just reinstalled Dropbox on a new machine, but getting "stop sign" notification at the very top bar of Ubuntu 18.04 Bionic with Gnome, instead of the usual notification with menus. Then after installing two packages:

- nautilus-dropbox
- gir1.2-nautilus-3.0

Still seeing as notification icon (with blank menu):
![stop sign notification icon](https://hdclipartall.com/images/prohibited-sign-clipart-px-prohibition-sign-image-232x300.png)

#### Any other possible remedies?

**Comment by rsvp** [comment]
hi @samertm Thanks for your response...

```
$ cat ~/.dropbox-dist/VERSION
63.4.107
```

In the meantime, I found out that when I upgraded from Ubuntu 16.04 to Ubuntu 18.04, the desktop environment continued to be Gnome metacity. Now that Ubuntu has abandoned Unity, the remaining alternatives off-the-self are: Gnome compiz, Ubuntu, or Ubuntu on Wayland.

Ok, so my problem was based on Gnome metacity, and when I ***switched to the "Ubuntu" default desktop environment the notification problem was fully resolved*** (and the now available menu is important in fine-tuning your sync preferences). When you log into your machine, and select your username, the password prompt appears. The desktop environment can then be selected by clicking on the "gears" icon. Hope this remedy helps others.

So there was no need to experiment with Dropbox beta v64. Happy New Years !!
