### ISSUE TITLE
Fedora: nautilus-dropbox uses obsolete python-gpg - should be python2-gpg

### ISSUE THREAD

**Issue by Ian2020** [dropbox/nautilus-dropbox#61]
Issue #51 fixed a problem with an obsolete package reference for Debian (and Ubuntu) but not for Fedora. In Fedora the package is now called `python2-gpg` I believe and the module to import is `gnupg`. Please could the fix be extended for those on Fedora? Thanks.

**Comment by samertm** [comment]
From a quick scan of fedora's `python2-gpg` package, it looks equivalent to `python-gpg` on Ubuntu/Debian, so the code will look the same.

We could change the rpm to suggest "python2-gpg" instead of "pygpgme", but that would fail on Fedora 21 (which is an issue because we currently build a single package for the oldest distro version we support and distribute that for all the versions, e.g. the Fedora 21 package is also used for Fedora 26).

Until we get the bandwidth to fix our build process to build multiple versions, my feeling is that it's better to use the obsolete package until Fedora removes it. What do you think?

**Comment by Ian2020** [comment]
Thanks, I agree it makes sense to stay with the obsolete package given the build restrictions.

So if I understand correctly  the answer is for those of us on Fedora 27+ is to simply install python2-gpg to enable the missing functionality. I've tested that on F29 and it works so I'm happy.

**Comment by samertm** [comment]
Yup, installing either `python2-gpg` or `pygpgme` will work on Fedora (at least until they get rid of `pygpgme`). :)
